add :bool to exists() in abstract adapter stub
cloudcreativity/laravel-json-api pull request #560
Opened 2020-10-10 11:16 UTC by daryledesilva

fixes this error on a freshly generated abstract adapter:
```
Declaration of App\JsonApi\Adapters\SearchResultAdapter::exists($resourceId) must be compatible with CloudCreativity\LaravelJsonApi\Contracts\Adapter\ResourceAdapterInterface::exists(string $resourceId): bool
```

2020-10-13 08:41 UTC, lindyhopchris requested changes
Thanks for submitting this. I hadn't spotted the stub was out of date! Just one change required to merge it.

2020-10-13 08:41 UTC, lindyhopchris commented on stubs/abstract/adapter.stub
> +    public function exists($resourceId): bool
This should be `exists(string $resourceId): bool`

2020-10-14 02:15 UTC, daryledesilva commented
> Thanks for submitting this. I hadn't spotted the stub was out of date! Just one change required to merge it.

Ok thanks! Done! If you merge my PR just squash it so it's cleaner 😁 cheers!

2020-10-14 09:01 UTC, lindyhopchris approved these changes

2020-10-14 09:01 UTC, merged